name: lhci-pr-comment-action
description: Install and run lhci and write comments on the pull request.
outputs:
  status:
    description: 生成できたかできなかったか
runs:
  using: composite
  steps:
    - name: install Lighthouse cli
      run: yarn add @lhci/cli@0.8.x

    - name: run Lighthouse cli 
      id: lhci
      run: |
        mkdir out
        touch out/autorun.txt
        yarn lhci autorun | grep 'storage.googleapis.com' > ./out/autorun.txt
        report_url=$(cat ./out/autorun.txt)
        echo $report_url
        echo "::set-output name=report_url::$report_url"
        continue-on-error: true
        env: 
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

    - name: json to markdown
      uses: shoma3571/lhci-format-action@v1.3
      id: parse
      with:
        json-file-path: .lighthouseci/assertion-results.json
        report-url: ${{ steps.lhci.outputs.report_url }}
      
    - name: post comment
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.html_url }}
      run: gh pr comment -F ./result-markdown.md "${URL}"
